### ISSUE TITLE
ERROR: `UTF32String` has no method matching UTF32String(::Array{Int32,1})

### ISSUE THREAD

**Issue by ddolgi** [samuelcolvin/uJSON.jl#1]
Yesterday, I compared some json parsers with uJSON.jl
When I parse a JSON document with uJSON.ji, I found an error above.
I solved it by replacing UTF32String() with utf32().
Is it a version problem?

My comparison is on:
https://gist.github.com/ddolgi/071f06624670342d1db8

ENV: julia version 0.3.4-pre+52

**Comment by freeboson** [comment]
I think this has been fixed in #2

**Comment by samuelcolvin** [comment]
Great, thanks.
